"""empty message

Revision ID: 2676eae410c5
Revises: b40e4f539cc2
Create Date: 2025-04-22 11:52:22.966163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2676eae410c5'
down_revision: Union[str, None] = 'b40e4f539cc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=900),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'description',
               existing_type=sa.String(length=900),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
