"""empty message

Revision ID: 7531eed2e08c
Revises: bf589912f3f0
Create Date: 2025-05-25 16:23:38.931307

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7531eed2e08c"
down_revision: Union[str, None] = "bf589912f3f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_primary_key("pk_profiles_id", "profiles", ["id"])

    op.create_table(
        "profile_photos",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("profile_id", sa.BigInteger(), nullable=False),
        sa.Column("photo", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute("""
        INSERT INTO profile_photos (profile_id, photo)
        SELECT id, photo FROM profiles WHERE photo IS NOT NULL
    """)
    op.drop_column("profiles", "photo")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("profiles", sa.Column("photo", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.execute("""
        UPDATE profiles
        SET photo = (
            SELECT photo FROM profile_photos
            WHERE profile_photos.profile_id = profiles.id
            ORDER BY id ASC LIMIT 1
        )
    """)
    op.drop_table("profile_photos")
    # ### end Alembic commands ###
