"""empty message

Revision ID: 758c4a6c1bd8
Revises: 0bbcda78e7e6
Create Date: 2025-02-09 17:54:39.008470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '758c4a6c1bd8'
down_revision: Union[str, None] = '0bbcda78e7e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
