"""Add instagram

Revision ID: b40e4f539cc2
Revises: a82a55fc2d78
Create Date: 2025-04-02 12:19:21.425621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b40e4f539cc2'
down_revision: Union[str, None] = 'a82a55fc2d78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('instagram', sa.String(length=200), nullable=True))
    op.alter_column('profiles', 'photo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'photo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('profiles', 'instagram')
    # ### end Alembic commands ###
